sudo: false
language: python
install: pip install -U tox coveralls
before_script:
  - echo 'Europe/Berlin' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdataafter_success: coveralls

matrix:
  fast_finish: true
  include:
    - python: "3.4.2"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=pylint

script: travis_wait tox
after_success: coveralls

deploy:
  provider: pypi
  user: christian.kuehnel
  password:
    secure: lpVC2QzACm5JicuhmxVeareZHLH4IPQsjpiMpUS6+OybZkGnIQyHI4qhcJ7TAgh4w5miwIXCNz1XFcPEZJKfpAC6WyuHiEeMZv4X2moCrFBTJZVmeBsO3UUIF+aixxeRYhR6ZX17VZczxfqF6K51L2twDmLbItzWS9mM998xOeHKqP48cSkiuU0ER8dXwZObLpLjitzxYvrtLRxpX6r5+A67rgwmsLHQyQAEMzlFURFaP7vMngEjGqIFUxXw4wEFsCXnfL4WWIo0awsJf2fYRZpYUUY4Hv2ZlspIZDojALKaRKjrEjyoxCXHG0rKmT7oPTJCPWJ+lIEMxJsZRGc7ZjDZt0GePvGDPNfaneqeQo1eBg5OqHrFe9IXlVDjNs/pV0dEJCv7fGsYHUXB5GHPLCioplT4HkDNTP9kpxAqBKMWVKCeAhB9+sLAmeuUkiH0vcZZhEJI370i5tFb3mzamdhZXIKUUHLaNgFN/XuohPPK9APYIjJl6AmtgysRgqWkpmETbTl3BrC4sMqdWPjLkUAepwGyuhL/kRKzxW0V0npwAWX9GnQdOi1dYuD50GlZOyjfxSTfFUs8ijIWEndwIeM3AiIP1OxKxTqsfY8zBwc58AMVArCGvsvjQb6PWt3JnDtcfex5GromiVzYguk04z2NGAPmqO9tDsEM8GnDM4g=
  on:
    tags: true